### PR TITLE
add option dialog and new icons

### PR DESCRIPTION
**Pull request by zdposter**

### CODE REVIEW

**Comment by arjanarcheologie** [comment]
Thanks a lot! 
Question: You suggest to add an options pane. I removed such a pane from a previous version as such a pane is provided by TB automatically. Could you elaborate why this might be better?

**Comment by zdposter** [comment]
Actually I did it [15 months ago](https://github.com/zdposter/move_messages_or_yourself) (starting from version 1.7.x)  and now I just transfer my changes. 
AFAIR I need to change shortcut (on windows) but I could not find options/preferences for it. I just tried 1.8 and I still do not find preferences/option there... Maybe I miss something.

**Comment by arjanarcheologie** [comment]
> Maybe I miss something.
Menu -> Tools -> Add-ons and Themes. This opens the "Add-ons Manager" pane.
Next, click the wheel to the right which shows a drop-down, click on 'manage extension shortcuts'.
Does that work on windows?

I'm on linux using TB102. In messagemove version 1.8 it does show the key shortcuts, see image. The textlabels left of the boxes are taken from the manifest.json.

image

**Comment by zdposter** [comment]
Thank you - yes this works for me - maybe you can put it to description of module. 

Anyway - are you interested in icon part? Your add on has default icon in TB, also icons takes less space than text label on at toolbar.

**Review by arjanarcheologie — APPROVED** [review]

**Pull request merged**
